var sum;
var sumtotal;
var wallet = 100.00;
const min = -5;
const max = 5;
const min2 = -4;
const max2 = 2;
const min3 = -15;
const max3 = 15;

const pmin = -5;
const pmax = 5;
const pmin2 = -7;
const pmax2 = 4;
const pmin3 = -100;
const pmax3 = 100;

var mywallet = document.querySelector(".urwallet");
var timerval = document.querySelector(".timer");
var timervalt = document.querySelector(".timert");
var timervalth = document.querySelector(".timerth");
var curr = document.querySelector(".curr");
//mywallet.innerHTML = 'My Wallet : $ ' + wallet;
var profvalue = document.querySelector('.prof');
var proftwo = document.querySelector('.proftwo');
var profth = document.querySelector('.profth');

var detail = document.querySelector('.cryp1_detail');
var detail2 = document.querySelector('.cryp2_detail');
var detail3 = document.querySelector('.cryp3_detail');


// for crypto 1
var compscore = (Math.random() * (max - min + 1)) + min;
var gainbyc1 = Math.floor((Math.random() * (pmax - pmin + 1)) + pmin );

// for crypto 2
var cryptwo = (Math.random() * (max2 - min2 + 1)) + min2;
var detailc2 = Math.floor((Math.random() * (pmax2 - pmin2 + 1)) + pmin2 );

// for 3rd crypto
var crypth = (Math.random() * (max3 - min3 + 1)) + min3;
var detailc3 = Math.floor((Math.random() * (pmax3 - pmin3 + 1)) + pmin3 );

var final = compscore.toFixed(2);
var final2 = cryptwo.toFixed(2);
var final3 = crypth.toFixed(2);




window.onload = function(){ 
 profvalue.innerHTML = final+' %';
 detail.innerHTML = 'Last month, avg. profit generated by this currency was $ '+  gainbyc1;
 detail2.innerHTML = 'Last month, avg. profit generated by this currency was $ '+  detailc2 ;
 detail3.innerHTML = 'Last month, avg. profit generated by this currency was $ '+  detailc3 ;
 
 proftwo.innerHTML = final2+' %';
 profth.innerHTML = final3+' %';
 
 
 if(final < 0){
     profvalue.style.color = "#d0312d";
 }else{
     profvalue.style.color = "green";
     profvalue.innerHTML = final+' %';
 }
 
 
 if(final2 < 0){
     proftwo.style.color = "#d0312d";
 }else{
     proftwo.style.color = "green";
     proftwo.innerHTML = '+'+final2+' %';
 }
 
 if(final3 < 0){
     profth.style.color = "#d0312d";
 }else{
     profth.style.color = "green";
     profth.innerHTML = '+'+final3+' %';
 }
 
 };
 
 const probmax = 50;
    const probmin = 0;
    const probmax2 = 80;
    const probmin2 = 0;
    const probmax3 = 100;
    const probmin3 = 0;
    
    var myInterval;
    
    var timer = 5;
    var timert = 5;
    var timerth = 5;
    var probval;
    var winprob;
    var probval2;
    var winprob2;
    var probval3;
    var winprob3;
    
    var up = document.querySelector('.up');
    var downa = document.querySelector('.downa');
    var up2 = document.querySelector('.upt');
    var downa2 = document.querySelector('.downat');
    var up3 = document.querySelector('.upth');
    var downa3 = document.querySelector('.downath');
    
    
    function timerfun(){
     
      myInterval = setInterval(timefun, 1000);         
     
     }
     
     function timefun(){     
        
        if(timer >= 0){
         
         timerval.innerHTML = timer;
         timer = timer - 1;
         
         }else{
            winprob = Number((Math.random() * (probmax - probmin + 1)) + probmin);
           probval = Number(Math.random().toFixed(2));
            
         // addition/substraction
         
            if(winprob < 22){
                timerval.innerHTML = 'YOU WIN : $ ' + probval;
                timer = 5;
                timerval.style.color = '#299617';
                
                
                sum = wallet + probval;
            
                mywallet.innerHTML = 'My Wallet : $'+ sum.toFixed(2);
            wallet = sum;
            
            
            clearInterval(myInterval); 
              }
              
              else if(winprob > 22){
            
                timerval.innerHTML = 'YOU LOSE : $ ' + probval;
                timerval.style.color = '#d0312d';
                timer = 5;
                
          
        
       sum = wallet - probval;
                
                mywallet.innerHTML ='My Wallet : $' +sum.toFixed(2) ;
            wallet = sum;
        
            clearInterval(myInterval); 
         }
         else{
             alert('Failed');
         }
          }
         
     downa.disabled = true;
     up.disabled = true;
     downa2.disabled = true;
     up2.disabled = true;
     downa3.disabled = true;
     up3.disabled = true;
     
     if(wallet < 0){
                mywallet.style.color = '#d0312d';
            }
     
 }
 function stopTimer(){
         timerval.innerHTML = '';
         timerval.style.color = '#3c07ad'
         downa.disabled = false;
         up.disabled = false;
         downa2.disabled = false;
         up2.disabled = false;
         downa3.disabled = false;
         up3.disabled = false;
     }
     
 // for 2nd crypto
 
 function timerfunt(){
     
      myInterval = setInterval(timefunt, 1000);         
     
     }
 
    function timefunt(){     
        
        if(timert >= 0){
         
         timervalt.innerHTML = timert;
         timert = timert - 1;
         
         }else{
            winprob2 = Number((Math.random() * (probmax2 - probmin2 + 1)) + probmin2);
           probval2 = Number(Math.random().toFixed(2));
                
                if(winprob2 <= 40){
                    timervalt.innerHTML = 'YOU WIN : $ ' + probval2;
                timert = 5;
                timervalt.style.color = '#299617';
                
                
                sum = wallet + probval2;
            
                mywallet.innerHTML = 'My Wallet : $'+ sum.toFixed(2);
            wallet = sum;
            
            clearInterval(myInterval); 
            downa2.disabled = true;
            up2.disabled = true;
                }
                else if(winprob2 > 40)
                {
                    timervalt.innerHTML = 'YOU LOSE : $ ' + probval2;
                timervalt.style.color = '#d0312d';
                timert = 5;
                
          
        
       sum = wallet - probval2;
                
                mywallet.innerHTML ='My Wallet : $' +sum.toFixed(2) ;
            wallet = sum;
        
            clearInterval(myInterval); 
            downa2.disabled = true;
            up2.disabled = true;
         }else{
             alert("Failed");
             downa2.disabled = true;
             up2.disabled = true;
         }
                
       }
     downa.disabled = true;
     up.disabled = true;
     downa2.disabled = true;
     up2.disabled = true;
     downa3.disabled = true;
     up3.disabled = true;
          
          
      if(wallet < 0){
                mywallet.style.color = '#d0312d';
            }     
     } 
     
       function stopTimert(){
         timervalt.innerHTML = '';
         timervalt.style.color = '#3c07ad'
         downa.disabled = false;
         up.disabled = false;
         downa2.disabled = false;
         up2.disabled = false;
         downa3.disabled = false;
         up3.disabled = false;
     }
 

// for 3rd crypto
 
 function timerfunth(){
     
      myInterval = setInterval(timefunth, 1000);         
     
     }
 
    function timefunth(){     
        
        if(timerth >= 0){
         
         timervalth.innerHTML = timerth;
         timerth = timerth - 1;
         
         }else{
            winprob3 = Number((Math.random() * (probmax3 - probmin3 + 1)) + probmin3);
           probval3 = Number(Math.random().toFixed(4));
            probval33 = probval3 * 100;
                
                if(winprob3 <= 40){
                    timervalth.innerHTML = 'YOU WIN : $ ' + probval33;
                timerth = 5;
                timervalth.style.color = '#299617';
                
                
                sum = wallet + probval33;
            
                mywallet.innerHTML = 'My Wallet : $'+ sum.toFixed(2);
            wallet = sum;
            
            clearInterval(myInterval); 
            downa3.disabled = true;
            up3.disabled = true;
                }
                else if(winprob3 > 40)
                {
                    timervalth.innerHTML = 'YOU LOSE : $ ' + probval33;
                timervalth.style.color = '#d0312d';
                timerth = 5;
                
          
        
       sum = wallet - probval33;
                
                mywallet.innerHTML ='My Wallet : $' +sum.toFixed(2) ;
            wallet = sum;
        
            clearInterval(myInterval); 
            downa3.disabled = true;
            up3.disabled = true;
         }else{
             alert("Failed");
             downa3.disabled = true;
             up3.disabled = true;
         }
                
       }
     downa.disabled = true;
     up.disabled = true;
     downa2.disabled = true;
     up2.disabled = true;
     downa3.disabled = true;
     up3.disabled = true;
      
      
      if(wallet < 0){
                mywallet.style.color = '#d0312d';
            }
           
     } 
     
       function stopTimerth(){
         timervalth.innerHTML = '';
         timervalth.style.color = '#3c07ad'
         downa.disabled = false;
         up.disabled = false;
         downa2.disabled = false;
         up2.disabled = false;
         downa3.disabled = false;
         up3.disabled = false;
     }
 
    if(wallet < 0){
                mywallet.style.color = '#d0312d';
            }
            
 